# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_taskflow
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: