# Generated by Django 5.2.5 on 2025-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_soon',
            field=models.BooleanField(default=False),
        ),
    ]
